apiVersion: v1
kind: Service # This is to expose the catalog-service application through kubernetes DNS service discover
metadata:
  name: catalog-service # Name of the service - must be a valid DNS name
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the Service
      targetPort: 9001 # Port exposed by the pods targeted by the service